# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hex < Formula
  desc "An opinionated Go application framework."
  homepage "https://github.com/jordanbrauer/hex"
  version "0.0.2-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.2-alpha/hex_0.0.2-alpha_darwin_x86_64.tar.gz"
      sha256 "ec32cf351fd9e18def723476785972a549423df80054d487d28fb3dfe6d22e39"

      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.2-alpha/hex_0.0.2-alpha_darwin_arm64.tar.gz"
      sha256 "edf0a1152539682cc6a85a8fe6e34ca0589031823398462f51e7586c1376f5ef"

      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.2-alpha/hex_0.0.2-alpha_linux_x86_64.tar.gz"
      sha256 "9514baf92496bc69229fbf373f3f834f633a3e37afe5df90d8522a31edc998cd"
      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.2-alpha/hex_0.0.2-alpha_linux_arm64.tar.gz"
      sha256 "867aff3a2c07ecf7d3ce82a1b0fe5e9d5a5efdca8faec6cf6539df20b7bc1577"
      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
  end

  test do
    system bin/"hex", "--help"
  end
end
