# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hex < Formula
  desc "An opinionated Go application framework."
  homepage "https://github.com/jordanbrauer/hex"
  version "0.0.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.1-alpha/hex_0.0.1-alpha_darwin_x86_64.tar.gz"
      sha256 "04f1bc8aa702a7bc04bad2b8a2eac45a4038498495846c4a4d3fc1e50a196f80"

      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.1-alpha/hex_0.0.1-alpha_darwin_arm64.tar.gz"
      sha256 "c819dda61e494fb88db2e958a65d8f2633cdd9755b4e0fc748d8a1a4ffe5a72a"

      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.1-alpha/hex_0.0.1-alpha_linux_x86_64.tar.gz"
      sha256 "77897d6be7752448a788c518037f1cc3a1ceacaae27ec2c71046c6c39057fdce"
      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jordanbrauer/hex/releases/download/v0.0.1-alpha/hex_0.0.1-alpha_linux_arm64.tar.gz"
      sha256 "b86fc6e48e080e0de3306d9d3787dcb8c502faffe1b0b73836eb220fcdfba7c8"
      define_method(:install) do
        bin.install "hex"
        man1.install "man/hex.1"
        man3.install "man/hex.3"
        man5.install "man/hex.5"
        man7.install "man/hex.7"
      end
    end
  end

  test do
    system bin/"hex", "--help"
  end
end
